version: '3.8'
services:
  mongodb:
    image: mongo:5.0
    container_name: bookhaven-mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - bookhaven_mongo_data:/data/db
volumes:
  bookhaven_mongo_data: 